# Generated by Django 4.1.6 on 2023-03-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_doctor_id_alter_paciente_id_alter_turnos_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='turnosDisp',
        ),
    ]
