# Generated by Django 4.1.6 on 2023-03-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_doctor_turnosdisp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='nombre',
        ),
    ]
