# Generated by Django 4.1.6 on 2023-03-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_doctor_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='especialidad',
            new_name='area',
        ),
        migrations.AddField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(default='doctorcito', max_length=30),
        ),
    ]
