# Generated by Django 4.1.6 on 2023-03-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_especialidad_doctor_area_doctor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='usuario',
            field=models.CharField(default='usu', max_length=30),
        ),
    ]
