# Generated by Django 4.1.6 on 2023-03-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_turnos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
    ]
