# Generated by Django 4.1.6 on 2023-03-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_turnos_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.CharField(default='doctorcito', max_length=30),
        ),
    ]
