# Generated by Django 4.1.6 on 2023-03-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_paciente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='dni',
            field=models.CharField(default='00000000', max_length=30),
        ),
    ]
