# Generated by Django 4.1.6 on 2023-03-31 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_nompaciente_turnos_paciente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turnos',
            new_name='Turno',
        ),
    ]
