# Generated by Django 4.1.6 on 2023-03-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_turnos_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.CharField(default='dd/mm/aa', max_length=30),
        ),
    ]
