# Generated by Django 4.1.6 on 2023-03-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_turno_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dni',
            field=models.CharField(default='00000000', max_length=30),
        ),
    ]
