# Generated by Django 4.1.6 on 2023-03-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_turno_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='usuario',
            field=models.CharField(default='doctorcito', max_length=30),
        ),
    ]
